// <auto-generated />
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File should have header", Justification = "Header not defined yet.", Scope = "namespace", Target = "~N:OnMRZ")]
